/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const INITIAL_POLL = 'INITIAL_POLL';
export const ADD_VOTE = 'ADD_VOTE';
export const VOTE_ASYNC_REQUEST = 'VOTE_ASYNC_REQUEST';
export const VOTE_ASYNC_SUCCESS = 'VOTE_ASYNC_SUCCESS';
export const VOTE_ASYNC_FAILURE = 'VOTE_ASYNC_FAILURE';
export const NEW_VOTE_ASYNC_REQUEST = 'NEW_VOTE_ASYNC_REQUEST';
export const NEW_VOTE_ASYNC_SUCCESS = 'NEW_VOTE_ASYNC_SUCCESS';
export const NEW_VOTE_ASYNC_FAILURE = 'NEW_VOTE_ASYNC_FAILURE';
